export const copy = {
  productName: "HandyHome",
  skipToContent: "Skip to content",
  navHome: "Home",
  navServices: "Services",
  navProfessionals: "Professionals",
  navSearch: "Search",
  navSignIn: "Sign in",
  navRegister: "Register",
  navGetStarted: "Get started",
  navMenu: "Menu",
  navDashboard: "Dashboard",
  navProfessionalDashboard: "Professional dashboard",
  navProfile: "Profile",
  navSignOut: "Sign out",
  homeAria: "HandyHome home",
  homeTitle: "Find local professionals for your home.",
  homeLead:
    "From plumbing and electrical work to cleaning and repairs, find the right professional for your needs.",
  heroKicker: "Home services in Casablanca",
  homeTitlePre: "Find",
  homeTitleAccent: "local professionals",
  homeTitlePost: "for your home.",
  heroSearchLabel: "What do you need help with?",
  heroSearchButton: "Search",
  heroBrowse: "Browse all professionals",
  heroChipQuote: "Quote before work starts",
  valueLocalTitle: "Local professionals",
  valueLocalBody: "Casablanca-area experts, listed with their services.",
  valueTimeTitle: "Real appointment times",
  valueTimeBody: "Book from the professional's own availability.",
  valueQuoteTitle: "Price on quote",
  valueQuoteBody: "You see the price after diagnosis, then decide.",
  journeyTitle: "From first search to finished job",
  journeyLead: "Five clear steps. You stay in control at every one.",
  journey1Title: "Find your service",
  journey1Body: "Search by service, city and date.",
  journey2Title: "Choose your professional",
  journey2Body: "Compare profiles, services and reviews.",
  journey3Title: "Pick a time",
  journey3Body: "Select a service and an available appointment.",
  journey4Title: "Receive your quote",
  journey4Body: "After the diagnosis, review the quote and accept it.",
  journey5Title: "Get it done",
  journey5Body: "The work is completed and you follow it to the end.",
  popularServicesLead: "Start from the job you need done.",
  allServices2: "All services",
  featuredLead: "Profiles with real services, areas and reviews from completed jobs.",
  allProfessionals: "View all professionals",
  whyTitle: "Built around how home repairs really work",
  whyLead: "No guessing at prices. No surprises halfway through.",
  whyDiagnosisTitle: "Diagnosis first",
  whyDiagnosisBody: "The professional assesses the job before any quote is made.",
  whyControlTitle: "You decide",
  whyControlBody: "Accept or decline the quote. Work starts only after you accept.",
  whyTrackTitle: "Follow every step",
  whyTrackBody: "See the status from request to completion on your dashboard.",
  whyReviewsTitle: "Honest reviews",
  whyReviewsBody: "Only clients with a completed, paid booking can leave a review.",
  homeCtaSecondary: "Explore services",
  homeSearchNeed: "What do you need?",
  homeSearchLocation: "Location",
  homeExploreServices: "Explore services",
  brandStoryTitle: "Your home. The right professional.",
  brandStoryLead: "HandyHome makes it easier to find local professionals for the jobs that matter.",
  exploreProfessionals: "Explore professionals",
  popularServices: "Popular home services",
  howItWorks: "How HandyHome works",
  howStep1Title: "Find",
  howStep1Body: "Find the service and professional you need.",
  howStep2Title: "Book",
  howStep2Body: "Choose a convenient appointment.",
  howStep3Title: "Get it done",
  howStep3Body: "Receive your quote and get your home service completed.",
  trustedNearby: "Meet local professionals",
  whyHandyHome: "Why HandyHome?",
  whyBookingTitle: "Clear booking process",
  whyBookingBody: "Request an intervention in a few steps, then follow the work through to completion.",
  whyLocalTitle: "Local professionals",
  whyLocalBody: "Work with nearby experts who know Casablanca homes.",
  whyQuotesTitle: "Quotes after diagnosis",
  whyQuotesBody: "Price on quote after a diagnosis. You accept before work continues.",
  whySimpleTitle: "Simple experience",
  whySimpleBody: "Search, book, review. HandyHome stays focused on getting the job done.",
  homeCtaTitle: "Need a hand at home?",
  homeCtaBody: "Find a professional for your next home service.",
  findProfessional: "Find a professional",
  footerTagline: "Home services made simple.",
  footerExplore: "Explore",
  footerPlace: "Made for homes in Casablanca",
  footerHow: "How it works",
  footerAccount: "Account",
  notFoundTitle: "Page not found",
  notFoundBody: "We could not find that page. It may have moved, or the link may be wrong.",
  notFoundAction: "Back to home",
  notFoundProfessional: "This professional profile was not found.",
  notFoundService: "This service was not found.",
  errorTitle: "Something went wrong",
  errorBody: "The page could not be displayed. Try again, or return home.",
  errorRetry: "Try again",
  loginTitle: "Sign in",
  loginLead: "Use your HandyHome email and password.",
  loginSubmit: "Sign in",
  loginNoAccount: "Need an account?",
  loginRegisterLink: "Register",
  registerTitle: "Create an account",
  registerLead: "Choose whether you are a client or a professional.",
  registerSubmit: "Create account",
  registerHasAccount: "Already have an account?",
  registerSignInLink: "Sign in",
  fieldName: "Full name",
  fieldEmail: "Email",
  fieldPassword: "Password",
  fieldRoleLegend: "I am registering as",
  roleClient: "I am a Client",
  roleProfessional: "I am a Professional",
  roleClientHint: "Request home services from professionals.",
  roleProfessionalHint: "Offer services. Your profile will not be verified yet.",
  authAsideTitle: "Home services, made simple.",
  authAside1: "Compare local professionals",
  authAside2: "Book a time that suits you",
  authAside3: "Accept a quote before work starts",
  authGenericError: "That email or password could not be used. Try again.",
  authInvalidCredentials: "Invalid email or password.",
  authDuplicateEmail: "An account with this email already exists.",
  authInvalidRole: "Choose Client or Professional.",
  clientDashboardTitle: "Client dashboard",
  clientWelcome: "Welcome back",
  clientDashboardLead: "Your current bookings and reviews are listed below.",
  professionalDashboardTitle: "Professional dashboard",
  professionalDashboardLead: "Today’s work, requests and quotes from your HandyHome bookings.",
  onboardingTitle: "Your profile is not public yet",
  onboardingLead: "Clients cannot find you in search until these steps are done:",
  onboardingProfession: "Add your profession",
  onboardingCity: "Add your city",
  onboardingServices: "Choose at least one service you offer",
  onboardingAction: "Complete your profile",
  onboardingNoAvailability:
    "No availability is listed for your profile yet, so clients can see you but cannot request appointments.",
  profileServicesLegend: "Services you offer",
  profileServicesHint: "Clients pick one of these when they request an intervention.",
  accountNotVerified: "This account is not verified.",
  signedInAs: "Signed in as",
  accountRole: "Account type",
  accountTypeClient: "Client account",
  accountTypeProfessional: "Professional account",
  browseProfessionals: "Browse professionals",
  browseServices: "Browse services",
  browseSearch: "Search professionals",
  searchTitle: "Find a professional",
  searchLead: "Search by service, city and date, then open a profile to book.",
  searchService: "Service",
  allServices: "All services",
  searchNeighborhood: "Neighborhood",
  searchDate: "Date",
  verifiedOnly: "Verified professionals only",
  searchSort: "Sort",
  sortName: "Name",
  sortNearest: "Nearest",
  searchSubmit: "Search",
  useMyLocation: "Use my location",
  geoUnsupported: "Location is not available in this browser.",
  geoDenied: "Location permission was denied.",
  geoTimeout: "Location request timed out.",
  geoUnavailable: "Your location could not be determined.",
  clearFilters: "Clear filters",
  searchResultsHeading: "Search results",
  searchCountOne: "1 professional found",
  searchCountMany: "{count} professionals found",
  searchCountOneOnDate: "1 professional available on {date}",
  searchCountManyOnDate: "{count} professionals available on {date}",
  searchEmpty: "No professionals found for this service and location.",
  searchEmptyHint: "Try another service or location.",
  searchEmptyOnDate: "No professionals available on that date.",
  searchEmptyHintOnDate: "Try another date, service or city.",
  searchQueryError: "Search results could not be loaded. Try again.",
  searchInvalid: "Those search filters could not be used.",
  searchLoading: "Loading search results.",
  searchMapLabel: "Map of matching professionals",
  mapTilesUnavailable: "Map tiles could not be loaded. The professional list is still available.",
  mapInitError: "The map could not start. The professional list is still available.",
  mapLoading: "Loading map",
  showMap: "Show map",
  hideMap: "Hide map",
  selectedProfessional: "Selected on map",
  showOnMap: "Show on map",
  nearestNeedsLocation: "Nearest sorting needs your location. Results are listed by name.",
  editProfile: "Edit profile",
  viewPublicProfile: "View public profile",
  professionalsTitle: "Professionals",
  professionalsHeading: "Find a professional",
  professionalsLead: "Local experts for your home.",
  emptyProfessionals: "No professionals available yet.",
  profilePrivateNotice:
    "Only you can see this page. Complete your profile to appear in search and accept booking requests.",
  noDescriptionYet: "No description yet.",
  loadingProfessionals: "Loading professionals.",
  loadingProfile: "Loading professional profile.",
  servicesTitle: "Services",
  servicesLead: "Repairs, maintenance and everyday home services in Casablanca.",
  emptyServices: "No services listed yet.",
  viewProfile: "View profile",
  viewService: "Explore",
  priceOnQuote: "Price on quote",
  professionalCountMany: "{count} professionals",
  profileBookingTitle: "Book this professional",
  profileBookingNote: "Choose a service and a time. The price is quoted after the diagnosis.",
  profileServices: "Services",
  profileLocation: "Location",
  profileAvailability: "Availability",
  profilePortfolio: "Portfolio",
  profileAbout: "About",
  emptyPortfolio: "No portfolio items yet.",
  emptyAvailability: "No availability listed yet.",
  emptyServiceProfessionals: "No professionals listed for this service yet.",
  portfolioItemFallback: "Portfolio item",
  fieldProfession: "Profession",
  fieldCity: "City",
  fieldDescription: "Description",
  saveProfile: "Save profile",
  profileSaved: "Profile saved.",
  profileEditTitle: "Edit your professional profile",
  profileEditLead: "Only you can change this public profile.",
  requestIntervention: "Request intervention",
  bookTitle: "Request intervention",
  bookLead: "Choose a service and an appointment. The professional will diagnose the issue later. Price on quote.",
  bookProfessional: "Professional",
  bookChooseService: "Choose service",
  bookDate: "Date",
  bookTimes: "Available times",
  bookTimezone: "Times are in Casablanca time.",
  bookSummaryEmpty: "Choose a service and a time to continue.",
  bookConfirm: "Request intervention",
  bookStepService: "Service",
  bookStepDate: "Date",
  bookStepTime: "Time",
  bookStepConfirm: "Confirm",
  bookSuccess: "Your intervention request has been submitted.",
  bookSuccessStatus: "Pending",
  bookViewDashboard: "View your bookings",
  bookingNeedSignIn: "Sign in as a client to request an intervention.",
  bookingProfessionalCannot: "Professionals cannot request an intervention as a client.",
  bookingNoAvailability: "No availability is currently listed for this professional.",
  bookingNoSlots: "No appointment times are currently available.",
  bookingUnavailable: "Booking is not available right now. Try again later.",
  quoteUnavailable: "Quote details are not available right now.",
  clientBookingsTitle: "Your bookings",
  clientBookingsEmpty: "You have not requested an intervention yet.",
  professionalBookingsTitle: "Incoming requests",
  professionalBookingsEmpty: "No intervention requests yet.",
  actionReviewQuote: "Review your quote",
  actionRecordPayment: "Record the payment status",
  actionLeaveReview: "Leave a review",
  actionAnswerRequest: "Accept or decline the request",
  actionStartDiagnosis: "Start the diagnosis",
  actionCompleteDiagnosis: "Complete the diagnosis",
  actionSendQuote: "Send a quote",
  actionStartIntervention: "Start the intervention",
  actionCompleteIntervention: "Complete the intervention",
  dashHello: "Hello, {name}",
  dashNextLabel: "Your next step",
  dashNextAppointment: "Next appointment",
  dashNeedsAction: "Needs your action",
  dashNothingToDo: "You're all caught up",
  dashNothingToDoBody: "There is nothing waiting on you right now.",
  dashGoToBooking: "Go to this booking",
  dashEmptyClientTitle: "Book your first professional",
  dashEmptyClientBody: "Search by service and area, then request an appointment.",
  dashEmptyProTitle: "No requests yet",
  dashEmptyProBody: "New requests from clients appear here as soon as they arrive.",
  dashLatest: "Latest updates",
  dashLatestEmpty: "Updates will appear here as your bookings move forward.",
  dashActiveWith: "With {name}",
  dashActiveFor: "For {name}",
  dashAwaiting: "Awaiting your action",
  dashAwaitingClient: "Quotes with clients",
  dashRequests: "New requests",
  dashCurrentStatusLabel: "Current status",
  dashboardCurrent: "Current booking",
  dashboardUpcoming: "Active bookings",
  dashboardNone: "None yet",
  dashboardCompleted: "Completed",
  dashboardReviews: "Reviews",
  dashboardToday: "Today's work",
  dashboardPendingRequests: "Pending requests",
  dashboardActiveInterventions: "Active interventions",
  dashboardQuotesWaiting: "Quotes awaiting response",
  dashboardCompletedJobs: "Completed jobs",
  bookingStatusRequested: "Pending",
  bookingStatusAccepted: "Accepted",
  bookingStatusRejected: "Declined",
  bookingStatusDiagnosis: "Diagnosis",
  bookingStatusQuoteSent: "Quote sent",
  bookingStatusQuoteAccepted: "Quote accepted",
  bookHelpTitle: "What happens next",
  bookHelpBody:
    "The professional reviews your request and accepts or declines it. You can follow the status on your dashboard. The price is set later, in a quote, after the professional has assessed the job.",
  hintClientRequested: "Waiting for the professional to accept your request.",
  hintClientAccepted: "Accepted. The professional will assess the job at your appointment.",
  hintClientDiagnosis: "The professional is assessing the job.",
  hintClientQuotePending: "A quote is waiting for your decision.",
  hintClientQuoteDeclined: "You declined the quote. The professional can send a new one.",
  hintClientQuoteAccepted: "Quote accepted. The intervention can now go ahead.",
  hintClientIntervention: "The work is being carried out.",
  hintClientPayment: "The work is done. Payment status is still pending.",
  hintClientCompleted: "Service completed.",
  hintClientRejected: "The professional declined this request.",
  hintProRequested: "Accept or decline this request.",
  hintProAccepted: "Start the diagnosis when you assess the job.",
  hintProDiagnosis: "Complete the diagnosis, then send a quote.",
  hintProQuotePending: "Waiting for the client to accept or decline your quote.",
  hintProQuoteDeclined: "The client declined your quote. You can send a new one.",
  hintProQuoteAccepted: "Start the intervention when you begin the work.",
  hintProIntervention: "Complete the intervention when the work is done.",
  hintProPayment: "Waiting for the client to record the payment status.",
  hintProCompleted: "Service completed.",
  hintProRejected: "You declined this request.",
  quoteDecisionTitle: "Quote awaiting your decision",
  quoteDecisionHelp: "Accepting lets the professional start the work at this price. You can also decline.",
  quoteTotal: "Quote total",
  progressStateDone: "completed",
  progressStateCurrent: "current step",
  progressStateUpcoming: "upcoming",
  bookingAccept: "Accept",
  bookingReject: "Decline",
  bookingAppointment: "Appointment",
  bookingClient: "Client",
  bookingService: "Service",
  bookingStatus: "Status",
  progressAccepted: "Booking accepted",
  progressDiagnosis: "Diagnosis",
  progressQuote: "Quote",
  progressIntervention: "Intervention",
  progressPayment: "Payment",
  progressCompleted: "Completed",
  diagnosisTitle: "Diagnosis",
  diagnosisPending: "Diagnosis pending",
  diagnosisCompleted: "Diagnosis completed",
  diagnosisDraft: "Diagnosis in progress",
  diagnosisFindings: "Diagnosis findings",
  startDiagnosis: "Start diagnosis",
  completeDiagnosis: "Complete diagnosis",
  quoteTitle: "Quote",
  quotePending: "Quote pending",
  quoteAwaitingClient: "Quote sent. Awaiting client.",
  quoteVersion: "Version",
  quoteAmount: "Amount",
  quoteNotes: "Professional notes",
  quoteDescription: "Description",
  sendQuote: "Send quote",
  acceptQuote: "Accept quote",
  declineQuote: "Decline quote",
  quoteAcceptedNext: "Quote accepted. The next step is to proceed with the intervention.",
  quoteDeclined: "Declined",
  quoteSent: "Sent",
  interventionPending: "Intervention pending",
  interventionInProgress: "Intervention in progress",
  startIntervention: "Start intervention",
  completeIntervention: "Complete intervention",
  interventionCompletedPaymentPending: "Intervention completed — payment pending",
  paymentPending: "Payment pending",
  paymentRecorded: "Payment recorded",
  recordPayment: "Record payment",
  recordPaymentHint:
    "This records a HandyHome payment state only. No card is charged and no payment provider is used.",
  paymentAmount: "Payment amount",
  amountHint: "Amount in MAD. Price is on quote until the client accepts.",
  reviewPrompt: "How was your experience?",
  reviewRating: "Rating",
  reviewRatingRequired: "required",
  reviewComment: "Share your experience",
  reviewCommentOptional: "optional",
  submitReview: "Submit review",
  reviewSubmitted: "Review submitted",
  leaveReview: "Leave a review",
  reviewsTitle: "Reviews",
  noReviewsYet: "No reviews yet",
  newProfessional: "New professional",
  reviewCountOne: "1 review",
  reviewCountMany: "{count} reviews",
  reviewAuthorFallback: "Client",
  assistantOpen: "Open HandyHome assistant",
  assistantClose: "Close HandyHome assistant",
  assistantTitle: "HandyHome Assistant",
  assistantBody:
    "Our assistant is coming soon. In the meantime, find a professional for your home service.",
} as const;
